version: '3.8'

services:
    server:
        image: rabbitmq:3-management
    dev:
        container_name: api_catalogo
        # image: api-catalogo:1.0.0
        links:
            - "server:server"
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        security_opt:
            - seccomp:unconfined
        env_file: .development.env
        command: npm run start:dev
        ports:
            - 3000:3000
            - 9229:9229
        extra_hosts:
            - "host.docker.internal:host-gateway"
            - localhost:192.168.100.30
        networks:
            - simples
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped


networks:
  simples:
    driver: bridge
    ipam:
      driver: default
